site_name: ECE 5831 at UM-D
theme: readthedocs

markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "_"

plugins:
    - pdf-export:
        verbose: true
        media_type: print
        enabled_if_env: ENABLE_PDF_EXPORT   

nav:
        - Home: index.md
        - 1. Environment Setup : env-setup/index.md
        - 1.1. Anaconda Installation: env-setup/install-anaconda.md
        - 2. Perceptron: perceptron/index.md
