site_name: ECE 5831 at UM-D
theme: readthedocs

markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "_"

nav:
        - Home: index.md
        - 1. Environment Setup : env-setup/index.md
        - 2. Perceptron: perceptron/index.md
